apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mongodb
        ports:
        - containerPort: 27017